version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "8000:8000"

  frontend:
    build: .
    volumes:
      - ./src:/App
    container_name: reactapp_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
